Repository dotnet/templating, pull requests merged in 2020-11, with the labels that each got.

#2610 add total downloads count to template search cache file
  src/Microsoft.TemplateSearch.Common/FileMetadataTemplateSearchCacheReader.cs
  src/Microsoft.TemplateSearch.Common/PackInfo.cs
  src/Microsoft.TemplateSearch.Common/PackToTemplateEntry.cs
  src/Microsoft.TemplateSearch.Common/TemplateToPackMap.cs
  src/Microsoft.TemplateSearch.TemplateDiscovery/Nuget/NugetPackInfo.cs
  src/Microsoft.TemplateSearch.TemplateDiscovery/Nuget/NugetPackProvider.cs
  src/Microsoft.TemplateSearch.TemplateDiscovery/Results/UnifiedPackCheckResultReportWriter.cs
Labels: triaged

#2619 Expected input for y/n is no longer part of localization string
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Microsoft.TemplateEngine.Cli/PostActionDispatcher.cs
Labels: triaged

#2620 --columns-all option
  src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/INewCommandInput.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/NewCommandInputCli.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/HelpForTemplateResolution.cs
  src/Microsoft.TemplateEngine.Cli/HelpFormatter.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  test/Microsoft.TemplateEngine.Cli.UnitTests/CliMocks/MockNewCommandInput.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/HelpTests/HelpFormatterTests.cs
Labels: triaged

#2608 Re-enabled unit tests that were previously commented out
  test/Microsoft.TemplateEngine.Core.UnitTests/OrchestratorTests.cs
  test/Microsoft.TemplateEngine.Edge.UnitTests/SettingsLoaderTests.cs
Labels: triaged

#2618 Filtering by author for dotnet list using --author option
  src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/FilterOption.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/INewCommandInput.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/NewCommandInputCli.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/SupportedFilterOptions.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/TemplateFilterOption.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/HelpForTemplateResolution.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/ListOrHelpTemplateListResolutionResult.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateListResolver.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateMatchInfoExtensions.cs
  src/Microsoft.TemplateEngine.Edge/Template/MatchLocation.cs
  src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/CliMocks/MockNewCommandInput.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/ListTemplateListResolverTests.cs
Labels: triaged

#2595 source name defaults to disk letter when template is created in root disk folder on Windows
  src/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs
Labels: triaged

#2612 Type filtering for templates should not consider the templates without type
  src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/ListTemplateListResolverTests.cs
Labels: triaged

#2649 [release/5.0] update branding to 5.0.1 servicing
  eng/Versions.props
Labels: triaged

#2635 Add folder .tye/ and .ionide/ to .gitignore template
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
Labels: need-pm-discussion, triaged

#2626 -- search option to search templates on Nuget
  src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/INewCommandInput.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/NewCommandInputCli.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/PackageFilterOption.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/SupportedFilterOptions.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/HelpForTemplateResolution.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Microsoft.TemplateEngine.Cli/New3Command.cs
  src/Microsoft.TemplateEngine.Cli/TableOutput/HelpFormatter.cs
  src/Microsoft.TemplateEngine.Cli/TableOutput/TemplateGroupDisplay.cs
  src/Microsoft.TemplateEngine.Cli/TableOutput/TemplateGroupTableRow.cs
  src/Microsoft.TemplateEngine.Cli/TemplateInvocationAndAcquisitionCoordinator.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateListResolver.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateMatchInfoExtensions.cs
  src/Microsoft.TemplateEngine.Cli/TemplateSearch/CliHostSpecificDataMatchFilter.cs
  src/Microsoft.TemplateEngine.Cli/TemplateSearch/CliTemplateSearchCoordinator.cs
  src/Microsoft.TemplateEngine.Cli/TemplateSearch/CliTemplateSearchCoordinatorFactory.cs
  src/Microsoft.TemplateEngine.Edge/Template/WellKnownSearchFilters.cs
  src/Microsoft.TemplateSearch.Common/FileMetadataTemplateSearchCache.cs
  src/Microsoft.TemplateSearch.Common/NuGetMetadataSearchSource.cs
  src/Microsoft.TemplateSearch.Common/TemplateSearcher.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/CliMocks/MockNewCommandInput.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/HelpTests/HelpFormatterTests.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateSearchCacheTests.cs
Labels: triaged

#2659 Fixing out of support TFM in restore shim
  src/Microsoft.TemplateEngine.Cli/Installer.cs
Labels: servicing-approved

#2622 Fix for the case when template instantiation fails when forms on file rename produce same result
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/FileRenameGenerator.cs
  test/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.UnitTests/TemplateConfigTests/FileRenameTests.cs
Labels: triaged

#2667 fixed error message for --search (wrong brackets order)
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Microsoft.TemplateEngine.Cli/PostActionProcessors/InstructionDisplayPostActionProcessor.cs
  src/Microsoft.TemplateEngine.Cli/TemplateSearch/CliTemplateSearchCoordinator.cs
Labels: triaged

#2662 fix for dotnet new failure if there's an invalidly pathed template installed
  src/Microsoft.TemplateEngine.Edge/Settings/SettingsLoader.cs
  test/Microsoft.TemplateEngine.Edge.UnitTests/SettingsLoaderTests.cs
  test/Microsoft.TemplateEngine.Mocks/MockMountPointManager.cs
Labels: triaged
