Repository dotnet/templating, pull requests merged in 2021-06, with the labels that each got.

#3173 enable nullable on new project templates
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj
  test/dotnet-new3.UnitTests/DotnetNewHelp.cs
Labels: need-pm-discussion, triaged

#3191 fixes dotnet/templating#3038 show all available short names for template group
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/HelpForTemplateResolution.cs
  src/Microsoft.TemplateEngine.Cli/TableOutput/TemplateGroupDisplay.cs
  src/Microsoft.TemplateEngine.Cli/TableOutput/TemplateGroupTableRow.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateGroup.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateInfoWithGroupShortNames.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateResolver.cs
  src/Microsoft.TemplateEngine.Cli/TemplateSearch/CliTemplateSearchCoordinator.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/MultiShortNameResolutionTests.cs
  test/dotnet-new3.UnitTests/DotnetNewInstantiate.cs
  test/dotnet-new3.UnitTests/DotnetNewList.cs
Labels: Priority:0, need-pm-discussion

#3234 fixes dotnet/templating#3113 disable partial matching on name for instantiation and --help
  src/Microsoft.TemplateEngine.Cli/Alias/AliasSupport.cs
  src/Microsoft.TemplateEngine.Cli/CommandParsing/INewCommandInputExtensions.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/InvalidParameterInfo.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/TemplateDetailsDisplay.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/TemplateInformationCoordinator.cs
  src/Microsoft.TemplateEngine.Cli/HelpAndUsage/TemplateUsageHelp.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Microsoft.TemplateEngine.Cli/New3Command.cs
  src/Microsoft.TemplateEngine.Cli/New3CommandStatus.cs
  src/Microsoft.TemplateEngine.Cli/TemplateInvocationCoordinator.cs
  src/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs
  src/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateListResolutionResult.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateResolutionResult.cs
  src/Microsoft.TemplateEngine.Cli/TemplateResolution/TemplateResolver.cs
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  test/Microsoft.TemplateEngine.Cli.IntegrationTests/FileRenameTests.cs
  test/Microsoft.TemplateEngine.Cli.TestHelper/Sdk/Assertions/CommandResultAssertions.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/HelpTests/TemplateInformationCoordinatorTests.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/HelpTemplateListResolverTests.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/ListTemplateListResolverTests.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/MultiShortNameResolutionTests.cs
  test/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/TemplateResolverTests.cs
  test/dotnet-new3.UnitTests/AllWebProjectsWork.cs
  test/dotnet-new3.UnitTests/DotnetNewHelp.cs
  test/dotnet-new3.UnitTests/DotnetNewInstantiate.cs
Labels: Priority:0, need-pm-discussion

#3253 Simple Console Application template
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/Microsoft.DotNet.Common.ProjectTemplates.6.0.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/App-CSharp/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/App-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/App-CSharp/Company.Application1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/App-CSharp/Program.cs
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj
  test/dotnet-new3.UnitTests/CommonTemplatesTests.cs
  test/dotnet-new3.UnitTests/DotnetNewHelp.cs
  test/dotnet-new3.UnitTests/DotnetNewList.cs
Labels: Priority:0

#3295 reverted setting CheckForOverflowUnderflow in project file for app and classlib template
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/App-CSharp/Company.Application1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj
  test/dotnet-new3.UnitTests/CommonTemplatesTests.cs
Labels: servicing-consider

#3299 do not enable nullable on netstandard2.0
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj
  test/dotnet-new3.UnitTests/CommonTemplatesTests.cs
Labels: servicing-consider
