Repository dotnet/templating, pull requests merged in 2022-11, with the labels that each got.

#5509 [release/6.0.4xx] adjusted tests for web templates
  test/dotnet-new3.UnitTests/AllWebProjectsWork.cs
Labels: servicing-approved

#5513 [release/6.0.3xx] adjusted tests for web templates
  test/dotnet-new3.UnitTests/AllWebProjectsWork.cs
Labels: servicing-approved

#5514 [release/6.0.1xx] adjusted tests for web templates
  test/dotnet-new3.UnitTests/AllWebProjectsWork.cs
Labels: servicing-approved

#5567 [release/6.0.4xx] Update System.Drawing.Common transitive dependency
  test/Microsoft.TemplateEngine.Cli.TestHelper/Microsoft.TemplateEngine.Cli.TestHelper.csproj
Labels: servicing-consider

#5630 [release/6.0.1xx] removed `dotnet-new3.VSIX`
  src/dotnet-new3.VSIX/CreateTemplateCommand.cs
  src/dotnet-new3.VSIX/InfoCollectorDialog.xaml
  src/dotnet-new3.VSIX/InfoCollectorDialog.xaml.cs
  src/dotnet-new3.VSIX/PrimaryPackage.cs
  src/dotnet-new3.VSIX/PrimaryPackage.vsct
  src/dotnet-new3.VSIX/Resources/CreateTemplateCommand.png
  src/dotnet-new3.VSIX/Resources/PrimaryPackage.ico
  src/dotnet-new3.VSIX/VSPackage.resx
  src/dotnet-new3.VSIX/WindowExtensions.cs
  src/dotnet-new3.VSIX/app.config
  src/dotnet-new3.VSIX/dotnet-new3.VSIX.csproj
  src/dotnet-new3.VSIX/packages.config
  src/dotnet-new3.VSIX/source.extension.vsixmanifest
Labels: servicing-approved

#5485 added test showcasing the behavior
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/BasicTests.cs
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/End2EndTests.cs
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/VerifySettingsFixture.cs
Labels: do-not-merge

#5659 [release/6.0.3xx] Remove dotnet-new3.VSIX
  src/dotnet-new3.VSIX/CreateTemplateCommand.cs
  src/dotnet-new3.VSIX/InfoCollectorDialog.xaml
  src/dotnet-new3.VSIX/InfoCollectorDialog.xaml.cs
  src/dotnet-new3.VSIX/PrimaryPackage.cs
  src/dotnet-new3.VSIX/PrimaryPackage.vsct
  src/dotnet-new3.VSIX/Resources/CreateTemplateCommand.png
  src/dotnet-new3.VSIX/Resources/PrimaryPackage.ico
  src/dotnet-new3.VSIX/VSPackage.resx
  src/dotnet-new3.VSIX/WindowExtensions.cs
  src/dotnet-new3.VSIX/app.config
  src/dotnet-new3.VSIX/dotnet-new3.VSIX.csproj
  src/dotnet-new3.VSIX/packages.config
  src/dotnet-new3.VSIX/source.extension.vsixmanifest
Labels: do-not-merge

#5660 [release/6.0.4xx] Remove dotnet-new3.VSIX
  src/dotnet-new3.VSIX/CreateTemplateCommand.cs
  src/dotnet-new3.VSIX/InfoCollectorDialog.xaml
  src/dotnet-new3.VSIX/InfoCollectorDialog.xaml.cs
  src/dotnet-new3.VSIX/PrimaryPackage.cs
  src/dotnet-new3.VSIX/PrimaryPackage.vsct
  src/dotnet-new3.VSIX/Resources/CreateTemplateCommand.png
  src/dotnet-new3.VSIX/Resources/PrimaryPackage.ico
  src/dotnet-new3.VSIX/VSPackage.resx
  src/dotnet-new3.VSIX/WindowExtensions.cs
  src/dotnet-new3.VSIX/app.config
  src/dotnet-new3.VSIX/dotnet-new3.VSIX.csproj
  src/dotnet-new3.VSIX/packages.config
  src/dotnet-new3.VSIX/source.extension.vsixmanifest
Labels: do-not-merge
