Repository dotnet/templating, pull requests merged in 2023-01, with the labels that each got.

#5718 Add named mutex to packing TestTemplates project for running multiple tests in parallel
  test/Microsoft.TemplateEngine.TestHelper/PackageManager.cs
Labels: servicing

#5816 [release/6.0.1xx] inverted language version conditions in console / classlib templates
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ConsoleApplication-CSharp/.template.config/template.json
  test/dotnet-new3.UnitTests/DotnetNewHelp.cs
Labels: servicing-consider, servicing

#5735 Re-enable signing validation after dotnet/arcade fixed it working with .NET 7.0
  azure-pipelines.yml
Labels: servicing

#5728 [release/6.0.4xx]conditions syntax test
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithBooleanParameters/.template.config/template.json
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithBooleanParameters/bar-computed.cs
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithBooleanParameters/bar.cs
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithBooleanParameters/bar.props
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithBooleanParameters/bar.vb
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=no options_options=bar-computed.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=no options_options=bar.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=no options_options=bar.props.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=no options_options=bar.vb.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to false_options=bar-computed.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to false_options=bar.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to false_options=bar.props.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to false_options=bar.vb.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to true_options=bar-computed.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to true_options=bar.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to true_options=bar.props.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=option equals to true_options=bar.vb.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=options without value_options=bar-computed.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=options without value_options=bar.cs.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=options without value_options=bar.props.verified.txt
  test/dotnet-new3.UnitTests/Approvals/DotnetNewInstantiate.ConditionSyntax_Test_testName=options without value_options=bar.vb.verified.txt
  test/dotnet-new3.UnitTests/DotnetNewInstantiate.cs
Labels: servicing

#5809 Adjust the place of overriding packages with version properties used in source build for Dependabot
  eng/Package.props
  eng/dependabot/Packages.props
Labels: servicing

#5826 removed `ITemplateEngineHost.OnParameterError` and other obsolete methods
  src/Microsoft.TemplateEngine.Abstractions/ITemplateEngineHost.cs
  src/Microsoft.TemplateEngine.Abstractions/Parameters/DataSource.cs
  src/Microsoft.TemplateEngine.Abstractions/PublicAPI.Shipped.txt
  src/Microsoft.TemplateEngine.Edge/DefaultTemplateEngineHost.cs
  src/Microsoft.TemplateEngine.Edge/PublicAPI.Shipped.txt
  src/Microsoft.TemplateEngine.Edge/Template/TemplateCreator.cs
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/ParameterConverter.cs
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectGenerator.cs
  test/Microsoft.TemplateEngine.TestHelper/TestHost.cs
Labels: breaking-change

#5944 [release/7.0.2xx] Add PreferDefaultName property (#5744)
  docs/Reference-for-template.json.md
  src/Microsoft.TemplateEngine.Abstractions/ITemplateInfo.cs
  src/Microsoft.TemplateEngine.Abstractions/PublicAPI.Unshipped.txt
  src/Microsoft.TemplateEngine.Edge/FilterableTemplateInfo.cs
  src/Microsoft.TemplateEngine.Edge/LocalizableStrings.Designer.cs
  src/Microsoft.TemplateEngine.Edge/LocalizableStrings.resx
  src/Microsoft.TemplateEngine.Edge/PublicAPI.Unshipped.txt
  src/Microsoft.TemplateEngine.Edge/Settings/TemplateInfo.cs
  src/Microsoft.TemplateEngine.Edge/Settings/TemplateInfoReader.cs
  src/Microsoft.TemplateEngine.Edge/Template/TemplateCreator.cs
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.cs.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.de.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.es.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.fr.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.it.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.ja.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.ko.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.pl.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.pt-BR.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.ru.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.tr.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.zh-Hans.xlf
  src/Microsoft.TemplateEngine.Edge/xlf/LocalizableStrings.zh-Hant.xlf
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/ConfigModel/TemplateConfigModel.cs
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/PublicAPI.Shipped.txt
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/PublicAPI.Unshipped.txt
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/RunnableProjectConfig.ITemplateInfo.cs
  src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Schemas/JSON/template.json
  src/Microsoft.TemplateSearch.Common/Abstractions/TemplateSearchData.cs
  src/Microsoft.TemplateSearch.Common/TemplateDiscoveryMetadata/BlobStorageTemplateInfo.cs
  test/Microsoft.TemplateEngine.Edge.UnitTests/GeneratorTests.cs
  test/Microsoft.TemplateEngine.Edge.UnitTests/TemplateCacheTests.cs
  test/Microsoft.TemplateEngine.Edge.UnitTests/TemplateCreatorTests.cs
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/Approvals/PreferDefaultNameTest.TestAssets.TemplateWithPreferDefaultName._.verified/TestAssets.TemplateWithPreferDefaultName/TestAssets.TemplateWithPreferDefaultName.cs
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/End2EndTests.cs
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/Microsoft.TemplateEngine.IDE.IntegrationTests.csproj
  test/Microsoft.TemplateEngine.IDE.IntegrationTests/SnapshotTests.cs
  test/Microsoft.TemplateEngine.Mocks/MockTemplateInfo.cs
  test/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.UnitTests/Serialization/TemplateConfigModelJsonConverter.cs
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithPreferDefaultName/.template.config/template.json
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithPreferDefaultName/toChange.cs
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithPreferDefaultNameButNoDefaultName/.template.config/template.json
  test/Microsoft.TemplateEngine.TestTemplates/test_templates/TemplateWithPreferDefaultNameButNoDefaultName/toChange.cs
  tools/Microsoft.TemplateSearch.TemplateDiscovery/Results/LegacyBlobTemplateInfo.cs
Labels: servicing-consider
